name: asistencias
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.1
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.0.1
  provider: ^6.1.1
  mobile_scanner: ^3.3.0
  fluttertoast: ^8.2.2
  intl: ^0.18.1   
  share_plus: ^7.0.0
  fl_chart: ^0.63.0
  flutter_tts: ^3.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
